---
# tasks file for deploy_app_server
  - name: ping Ubuntu Server
    ping:

  - name: Update the System Packages
    apt:
      update_cache: yes

  - name: Install openjdk-11-jdk
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Create a Tomcat Group
    group:
      name: tomcat

  - name: Create a Tomcat User
    user:
      name: tomcat
      group: tomcat
      createhome: no

  - name: Create a Tomcat Directory
    file:
      path: /opt/tomcat
      state: directory
      owner: tomcat
      group: tomcat
      mode: 0755

  - name: download & unarchive tomcat
    unarchive:
      src: https://www-eu.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_ver }}/bin/apache-tomcat-{{ tomcat_ver }}.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership of tomcat directory
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
      src: tomcat.service
      dest: "{{ path_to_serv_file }}"
      mode: 0755

  - name: Start and Enable Tomcat 9 on Ubuntu sever
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true

  - name: Install Maven
    apt:
      name: maven
      state: present

